fields:
  - 0.3_um_count
  - 0.5_um_count
  - 1.0_um_count
  - 2.5_um_count
  - 5.0_um_count
  - 10.0_um_count
  - deciviews
  - humidity
  - pm1.0_atm
  - pm1.0_cf_1
  - pm2.5_alt
  - pm2.5_atm
  - pm2.5_cf_1
  - pm10.0_atm
  - pm10.0_cf_1
  - pressure
  - scattering_coefficient
  - temperature
  - voc
sensors:
  - name: WCAN-105
    id: 273843
  - name: WCAN-106
    id: 270396
  - name: WCAN-51
    id: 270280
  - name: WCAN-9
    id: 270374
  - name: WCAN-100
    id: 272224
  - name: WCAN-98
    id: 272190
  - name: WCAN-48
    id: 270334
  - name: WCAN-58
    id: 272232
  - name: WCAN-90
    id: 272260
  - name: WCAN-14
    id: 273831
  - name: WCAN-15
    id: 270404
  - name: WCAN-68
    id: 272214

time_average: 60
